apiVersion: v1
kind: Service
metadata:
  name: Atharvadeploytesting7
  namespace: default
  labels:
    app: Atharvadeploytesting7
spec:
  type: ClusterIP
  selector:
    app: Atharvadeploytesting7
  ports:
    - name: ftp
      protocol: FTP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Atharvadeploytesting7
  namespace: default
  labels:
    app: Atharvadeploytesting7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Atharvadeploytesting7
  template:
    metadata:
      labels:
        app: Atharvadeploytesting7
    spec:
      containers:
        - name: Atharvadeploytesting7-container
          image: 891376929531.dkr.ecr.ap-south-1.amazonaws.com//cost-analyzer-atharva1889-tfucl:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-atharva-ecr-aws-ecr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Atharvadeploytesting7
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: atharva-s4-kgujb.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: Atharvadeploytesting7
                port:
                  number: 80
  tls:
    - hosts:
        - atharva-s4-kgujb.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
