apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoutflo-sa-metabaseabtest2ok
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891376929531:role/Scoutflo-cloud-credentials-3272ca00-3b68-4272-8e2d-90327b6c3965

---
apiVersion: v1
kind: Service
metadata:
  name: metabaseabtest2ok
  namespace: default
  labels:
    app: metabaseabtest2ok
spec:
  type: ClusterIP
  selector:
    app: metabaseabtest2ok
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabaseabtest2ok
  namespace: default
  labels:
    app: metabaseabtest2ok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabaseabtest2ok
  template:
    metadata:
      labels:
        app: metabaseabtest2ok
    spec:
      serviceAccountName: scoutflo-sa-metabaseabtest2ok
      containers:
        - name: metabaseabtest2ok-container
          image: 891376929531.dkr.ecr.ap-south-2.amazonaws.com/waitlist-private:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m
          env: []

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabaseabtest2ok
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: iugeidgwefgeuf-znonu.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabaseabtest2ok
                port:
                  number: 80
  tls:
    - hosts:
        - iugeidgwefgeuf-znonu.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
