apiVersion: v1
kind: Service
metadata:
  name: judge0-test1
  namespace: dev-byu
  labels:
    app: judge0-test1
spec:
  type: ClusterIP
  selector:
    app: judge0-test1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-test1
  namespace: dev-byu
  labels:
    app: judge0-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0-test1
  template:
    metadata:
      labels:
        app: judge0-test1
    spec:
      containers:
        - name: judge0-test1-container
          image: scoutflo/judge0:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-scoutflo-docker-docker
