apiVersion: v1
kind: Service
metadata:
  name: judge0-ab1
  namespace: default
  labels:
    app: judge0-ab1
spec:
  type: ClusterIP
  selector:
    app: judge0-ab1
  ports:
    - name: https
      protocol: TCP
      port: 2358
      targetPort: 2358

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-ab1
  namespace: default
  labels:
    app: judge0-ab1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: judge0-ab1
  template:
    metadata:
      labels:
        app: judge0-ab1
    spec:
      containers:
        - name: judge0-ab1-container
          image: scoutflo/judge0:latest
          ports:
            - containerPort: 2358
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-scoutflo-docker-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge0-ab1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: judge0-kgreu.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: judge0-ab1
                port:
                  number: 2358
  tls:
    - hosts:
        - judge0-kgreu.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
