apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: dev-byu
  labels:
    app: test2
spec:
  type: ClusterIP
  selector:
    app: test2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  namespace: dev-byu
  labels:
    app: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
        - name: test2-container
          image: scoutflo/judge0:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: NODE_ENV
              value: production
      imagePullSecrets:
        - name: scoutflo-scoutflo-docker-docker
